import { cn } from "@monorepo/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const clash = localFont({
  src: "../fonts/clash-display.otf",
  variable: "--font-clash",
});

export const metadata: Metadata = {
  title: "The Monorepo",
  description: "Generated by @bharathxd",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
        <body className={cn("min-h-screen bg-background antialiased", inter.variable, clash.variable)}>{children}</body>
    </html>
  );
}
